name: "Bug Report: Wrath"
description: Report a bug for Wrath
title: "Title here"
labels: ['🐛 Needs Investigation ❓', '🧬 Wrath ❄️']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What is the issue you are having?
      description: Describe the issue and what was going on when it happened?
      placeholder: Give us an explaination of what was going on when the issue appeared.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior and what actually happened?
      description: Please try to be as descriptive as possible.
      placeholder: Try to explain what happened and what you expected the outcome to be.
    validations:
      required: true
  - type: textarea
    id: repoduce-steps
    attributes:
      label: Reproducing the issue.
      description: List steps in order to reproduce this issue.
      placeholder: "Please make sure to use the debug command first: /edebug on"
    validations:
      required: false
  - type: textarea
    id: errors
    attributes:
      label: Lua Errors
      description: If you have any Lua errors, please put them here. The first error is most important.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Changelog & Troubleshooting
      description: By submitting this issue, you agree you followed our [Troubleshooting Steps](https://github.com/tukui-org/ElvUI/wiki/troubleshoot)
      options:
        - label: I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md)
          required: true
        - label: I have verified [ElvUI](https://tukui.org/elvui) is up to date by checking `/estatus`
          required: true
        - label: I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues)
          required: true
        - label: I have not read any of these steps, please close my issue when you see it.
        - label: I have tested with `/edebug on` **This is important in order to rule out that any of your other addons are causing the issue.**
          required: true
