name: "Bug Report: Retail"
description: Report a bug in ElvUI for Retail
title: "Title here"
labels: ['🐛 Needs Investigation ❓', '🧬 Retail 🐲']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What is the issue you are having?
      description: Describe the issue and what was going on when it happened?
      placeholder: Give us an explaination of what was going on when the issue appeared.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: What do you think the expected behavior should have happened?
      placeholder: Try to explain what you expected the outcome to be.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: What actually happened?
      description: Please try to be as descriptive as possible.
      placeholder: Try to explain what happened.
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution
      description: If you have any idea how we could solve it let us know.
  - type: textarea
    id: errors
    attributes:
      label: Errors
      description: If you have any errors, please put them here.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: ElvUI Changelog & Troubleshooting
      description: I will the troubleshooting steps and included the requested screenshot and understand if not, the ticket will be closed. 
      options:
        - label: I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
          required: true
        - label: I have verified my issue doesn't exist in the Default UI or ElvUI Issue Tracker.
          required: true
        - label: What is the issue you are having?
          placeholder: Please go through the troubleshooting steps and provide the requested information and a description of the issue.
          description: 1. Type in chat in game `/edebug on`
                       2. Test.  Do you still have the issue?
                       3. If so, type in chat in game `/estatus` and verify ElvUI is up to date
                       4. upload a FULL UI screenshot (no cropping) showing both the issue and the status panel. 
